// DO NOT EDIT. The code is generated by Local Rust Cloud models gen tool.

#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(std::clone::Clone, std::cmp::PartialEq, std::fmt::Debug)]
pub struct CreatePolicyRequest {
}

/// <p>Contains the response to a successful <a>CreatePolicy</a> request.
///     </p>
#[non_exhaustive]
#[derive(std::clone::Clone, std::cmp::PartialEq, std::fmt::Debug)]
pub struct CreatePolicyResponse {
}

