use std::collections::HashMap;

use actix_http::{
    body::BoxBody,
    header::{HeaderName, HeaderValue},
    StatusCode,
};
use actix_web::{web::Data, HttpRequest, HttpResponse};
use futures::executor::block_on;
use local_rust_cloud_common::service_handler::ServiceHandler;
use local_rust_cloud_sqlite::Database;
use uuid::Uuid;

use super::{errors::IamApiError, query::QueryReader, response::IamResponse};

pub enum Iam {
    AddRoleToInstanceProfile,
    AddUserToGroup,
    AttachGroupPolicy,
    AttachRolePolicy,
    AttachUserPolicy,
    ChangePassword,
    CreateAccessKey,
    CreateAccountAlias,
    CreateGroup,
    CreateInstanceProfile,
    CreateLoginProfile,
    CreateOpenIdConnectProvider,
    CreatePolicy,
    CreatePolicyVersion,
    CreateRole,
    CreateSamlProvider,
    CreateServiceLinkedRole,
    CreateServiceSpecificCredential,
    CreateUser,
    CreateVirtualMfaDevice,
    DeactivateMfaDevice,
    DeleteAccessKey,
    DeleteAccountAlias,
    DeleteAccountPasswordPolicy,
    DeleteGroup,
    DeleteGroupPolicy,
    DeleteInstanceProfile,
    DeleteLoginProfile,
    DeleteOpenIdConnectProvider,
    DeletePolicy,
    DeletePolicyVersion,
    DeleteRole,
    DeleteRolePermissionsBoundary,
    DeleteRolePolicy,
    DeleteSamlProvider,
    DeleteServerCertificate,
    DeleteServiceLinkedRole,
    DeleteServiceSpecificCredential,
    DeleteSigningCertificate,
    DeleteSshPublicKey,
    DeleteUser,
    DeleteUserPermissionsBoundary,
    DeleteUserPolicy,
    DeleteVirtualMfaDevice,
    DetachGroupPolicy,
    DetachRolePolicy,
    DetachUserPolicy,
    EnableMfaDevice,
    GenerateCredentialReport,
    GenerateOrganizationsAccessReport,
    GenerateServiceLastAccessedDetails,
    GetAccessKeyLastUsed,
    GetAccountAuthorizationDetails,
    GetAccountPasswordPolicy,
    GetAccountSummary,
    GetContextKeysForCustomPolicy,
    GetContextKeysForPrincipalPolicy,
    GetCredentialReport,
    GetGroup,
    GetGroupPolicy,
    GetInstanceProfile,
    GetLoginProfile,
    GetMfaDevice,
    GetOpenIdConnectProvider,
    GetOrganizationsAccessReport,
    GetPaginator,
    GetPolicy,
    GetPolicyVersion,
    GetRole,
    GetRolePolicy,
    GetSamlProvider,
    GetServerCertificate,
    GetServiceLastAccessedDetails,
    GetServiceLastAccessedDetailsWithEntities,
    GetServiceLinkedRoleDeletionStatus,
    GetSshPublicKey,
    GetUser,
    GetUserPolicy,
    GetWaiter,
    ListAccessKeys,
    ListAccountAliases,
    ListAttachedGroupPolicies,
    ListAttachedRolePolicies,
    ListAttachedUserPolicies,
    ListEntitiesForPolicy,
    ListGroupPolicies,
    ListGroups,
    ListGroupsForUser,
    ListInstanceProfileTags,
    ListInstanceProfiles,
    ListInstanceProfilesForRole,
    ListMfaDeviceTags,
    ListMfaDevices,
    ListOpenIdConnectProviderTags,
    ListOpenIdConnectProviders,
    ListPolicies,
    ListPoliciesGrantingServiceAccess,
    ListPolicyTags,
    ListPolicyVersions,
    ListRolePolicies,
    ListRoleTags,
    ListRoles,
    ListSamlProviderTags,
    ListSamlProviders,
    ListServerCertificateTags,
    ListServerCertificates,
    ListServiceSpecificCredentials,
    ListSigningCertificates,
    ListSshPublicKeys,
    ListUserPolicies,
    ListUserTags,
    ListUsers,
    ListVirtualMfaDevices,
    PutGroupPolicy,
    PutRolePermissionsBoundary,
    PutRolePolicy,
    PutUserPermissionsBoundary,
    PutUserPolicy,
    RemoveClientIdFromOpenIdConnectProvider,
    RemoveRoleFromInstanceProfile,
    RemoveUserFromGroup,
    ResetServiceSpecificCredential,
    ResyncMfaDevice,
    SetDefaultPolicyVersion,
    SetSecurityTokenServicePreferences,
    SimulateCustomPolicy,
    SimulatePrincipalPolicy,
    TagInstanceProfile,
    TagMfaDevice,
    TagOpenIdConnectProvider,
    TagPolicy,
    TagRole,
    TagSamlProvider,
    TagServerCertificate,
    TagUser,
    UntagInstanceProfile,
    UntagMfaDevice,
    UntagOpenIdConnectProvider,
    UntagPolicy,
    UntagRole,
    UntagSamlProvider,
    UntagServerCertificate,
    UntagUser,
    UpdateAccessKey,
    UpdateAccountPasswordPolicy,
    UpdateAssumeRolePolicy,
    UpdateGroup,
    UpdateLoginProfile,
    UpdateOpenIdConnectProviderThumbprint,
    UpdateRole,
    UpdateRoleDescription,
    UpdateSamlProvider,
    UpdateServerCertificate,
    UpdateServiceSpecificCredential,
    UpdateSigningCertificate,
    UpdateSshPublicKey,
    UpdateUser,
    UploadServerCertificate,
    UploadSigningCertificate,
    UploadSshPublicKey,
    Unknown,
}

impl Iam {
    pub fn from_str(action_name: &str) -> Self {
        match action_name {
            "AddRoleToInstanceProfile" => Iam::AddRoleToInstanceProfile,
            "AddUserToGroup" => Iam::AddUserToGroup,
            "AttachGroupPolicy" => Iam::AttachGroupPolicy,
            "AttachRolePolicy" => Iam::AttachRolePolicy,
            "AttachUserPolicy" => Iam::AttachUserPolicy,
            "ChangePassword" => Iam::ChangePassword,
            "CreateAccessKey" => Iam::CreateAccessKey,
            "CreateAccountAlias" => Iam::CreateAccountAlias,
            "CreateGroup" => Iam::CreateGroup,
            "CreateInstanceProfile" => Iam::CreateInstanceProfile,
            "CreateLoginProfile" => Iam::CreateLoginProfile,
            "CreateOpenIdConnectProvider" => Iam::CreateOpenIdConnectProvider,
            "CreatePolicy" => Iam::CreatePolicy,
            "CreatePolicyVersion" => Iam::CreatePolicyVersion,
            "CreateRole" => Iam::CreateRole,
            "CreateSamlProvider" => Iam::CreateSamlProvider,
            "CreateServiceLinkedRole" => Iam::CreateServiceLinkedRole,
            "CreateServiceSpecificCredential" => Iam::CreateServiceSpecificCredential,
            "CreateUser" => Iam::CreateUser,
            "CreateVirtualMfaDevice" => Iam::CreateVirtualMfaDevice,
            "DeactivateMfaDevice" => Iam::DeactivateMfaDevice,
            "DeleteAccessKey" => Iam::DeleteAccessKey,
            "DeleteAccountAlias" => Iam::DeleteAccountAlias,
            "DeleteAccountPasswordPolicy" => Iam::DeleteAccountPasswordPolicy,
            "DeleteGroup" => Iam::DeleteGroup,
            "DeleteGroupPolicy" => Iam::DeleteGroupPolicy,
            "DeleteInstanceProfile" => Iam::DeleteInstanceProfile,
            "DeleteLoginProfile" => Iam::DeleteLoginProfile,
            "DeleteOpenIdConnectProvider" => Iam::DeleteOpenIdConnectProvider,
            "DeletePolicy" => Iam::DeletePolicy,
            "DeletePolicyVersion" => Iam::DeletePolicyVersion,
            "DeleteRole" => Iam::DeleteRole,
            "DeleteRolePermissionsBoundary" => Iam::DeleteRolePermissionsBoundary,
            "DeleteRolePolicy" => Iam::DeleteRolePolicy,
            "DeleteSamlProvider" => Iam::DeleteSamlProvider,
            "DeleteServerCertificate" => Iam::DeleteServerCertificate,
            "DeleteServiceLinkedRole" => Iam::DeleteServiceLinkedRole,
            "DeleteServiceSpecificCredential" => Iam::DeleteServiceSpecificCredential,
            "DeleteSigningCertificate" => Iam::DeleteSigningCertificate,
            "DeleteSshPublicKey" => Iam::DeleteSshPublicKey,
            "DeleteUser" => Iam::DeleteUser,
            "DeleteUserPermissionsBoundary" => Iam::DeleteUserPermissionsBoundary,
            "DeleteUserPolicy" => Iam::DeleteUserPolicy,
            "DeleteVirtualMfaDevice" => Iam::DeleteVirtualMfaDevice,
            "DetachGroupPolicy" => Iam::DetachGroupPolicy,
            "DetachRolePolicy" => Iam::DetachRolePolicy,
            "DetachUserPolicy" => Iam::DetachUserPolicy,
            "EnableMfaDevice" => Iam::EnableMfaDevice,
            "GenerateCredentialReport" => Iam::GenerateCredentialReport,
            "GenerateOrganizationsAccessReport" => Iam::GenerateOrganizationsAccessReport,
            "GenerateServiceLastAccessedDetails" => Iam::GenerateServiceLastAccessedDetails,
            "GetAccessKeyLastUsed" => Iam::GetAccessKeyLastUsed,
            "GetAccountAuthorizationDetails" => Iam::GetAccountAuthorizationDetails,
            "GetAccountPasswordPolicy" => Iam::GetAccountPasswordPolicy,
            "GetAccountSummary" => Iam::GetAccountSummary,
            "GetContextKeysForCustomPolicy" => Iam::GetContextKeysForCustomPolicy,
            "GetContextKeysForPrincipalPolicy" => Iam::GetContextKeysForPrincipalPolicy,
            "GetCredentialReport" => Iam::GetCredentialReport,
            "GetGroup" => Iam::GetGroup,
            "GetGroupPolicy" => Iam::GetGroupPolicy,
            "GetInstanceProfile" => Iam::GetInstanceProfile,
            "GetLoginProfile" => Iam::GetLoginProfile,
            "GetMfaDevice" => Iam::GetMfaDevice,
            "GetOpenIdConnectProvider" => Iam::GetOpenIdConnectProvider,
            "GetOrganizationsAccessReport" => Iam::GetOrganizationsAccessReport,
            "GetPaginator" => Iam::GetPaginator,
            "GetPolicy" => Iam::GetPolicy,
            "GetPolicyVersion" => Iam::GetPolicyVersion,
            "GetRole" => Iam::GetRole,
            "GetRolePolicy" => Iam::GetRolePolicy,
            "GetSamlProvider" => Iam::GetSamlProvider,
            "GetServerCertificate" => Iam::GetServerCertificate,
            "GetServiceLastAccessedDetails" => Iam::GetServiceLastAccessedDetails,
            "GetServiceLastAccessedDetailsWithEntities" => Iam::GetServiceLastAccessedDetailsWithEntities,
            "GetServiceLinkedRoleDeletionStatus" => Iam::GetServiceLinkedRoleDeletionStatus,
            "GetSshPublicKey" => Iam::GetSshPublicKey,
            "GetUser" => Iam::GetUser,
            "GetUserPolicy" => Iam::GetUserPolicy,
            "GetWaiter" => Iam::GetWaiter,
            "ListAccessKeys" => Iam::ListAccessKeys,
            "ListAccountAliases" => Iam::ListAccountAliases,
            "ListAttachedGroupPolicies" => Iam::ListAttachedGroupPolicies,
            "ListAttachedRolePolicies" => Iam::ListAttachedRolePolicies,
            "ListAttachedUserPolicies" => Iam::ListAttachedUserPolicies,
            "ListEntitiesForPolicy" => Iam::ListEntitiesForPolicy,
            "ListGroupPolicies" => Iam::ListGroupPolicies,
            "ListGroups" => Iam::ListGroups,
            "ListGroupsForUser" => Iam::ListGroupsForUser,
            "ListInstanceProfileTags" => Iam::ListInstanceProfileTags,
            "ListInstanceProfiles" => Iam::ListInstanceProfiles,
            "ListInstanceProfilesForRole" => Iam::ListInstanceProfilesForRole,
            "ListMfaDeviceTags" => Iam::ListMfaDeviceTags,
            "ListMfaDevices" => Iam::ListMfaDevices,
            "ListOpenIdConnectProviderTags" => Iam::ListOpenIdConnectProviderTags,
            "ListOpenIdConnectProviders" => Iam::ListOpenIdConnectProviders,
            "ListPolicies" => Iam::ListPolicies,
            "ListPoliciesGrantingServiceAccess" => Iam::ListPoliciesGrantingServiceAccess,
            "ListPolicyTags" => Iam::ListPolicyTags,
            "ListPolicyVersions" => Iam::ListPolicyVersions,
            "ListRolePolicies" => Iam::ListRolePolicies,
            "ListRoleTags" => Iam::ListRoleTags,
            "ListRoles" => Iam::ListRoles,
            "ListSamlProviderTags" => Iam::ListSamlProviderTags,
            "ListSamlProviders" => Iam::ListSamlProviders,
            "ListServerCertificateTags" => Iam::ListServerCertificateTags,
            "ListServerCertificates" => Iam::ListServerCertificates,
            "ListServiceSpecificCredentials" => Iam::ListServiceSpecificCredentials,
            "ListSigningCertificates" => Iam::ListSigningCertificates,
            "ListSshPublicKeys" => Iam::ListSshPublicKeys,
            "ListUserPolicies" => Iam::ListUserPolicies,
            "ListUserTags" => Iam::ListUserTags,
            "ListUsers" => Iam::ListUsers,
            "ListVirtualMfaDevices" => Iam::ListVirtualMfaDevices,
            "PutGroupPolicy" => Iam::PutGroupPolicy,
            "PutRolePermissionsBoundary" => Iam::PutRolePermissionsBoundary,
            "PutRolePolicy" => Iam::PutRolePolicy,
            "PutUserPermissionsBoundary" => Iam::PutUserPermissionsBoundary,
            "PutUserPolicy" => Iam::PutUserPolicy,
            "RemoveClientIdFromOpenIdConnectProvider" => Iam::RemoveClientIdFromOpenIdConnectProvider,
            "RemoveRoleFromInstanceProfile" => Iam::RemoveRoleFromInstanceProfile,
            "RemoveUserFromGroup" => Iam::RemoveUserFromGroup,
            "ResetServiceSpecificCredential" => Iam::ResetServiceSpecificCredential,
            "ResyncMfaDevice" => Iam::ResyncMfaDevice,
            "SetDefaultPolicyVersion" => Iam::SetDefaultPolicyVersion,
            "SetSecurityTokenServicePreferences" => Iam::SetSecurityTokenServicePreferences,
            "SimulateCustomPolicy" => Iam::SimulateCustomPolicy,
            "SimulatePrincipalPolicy" => Iam::SimulatePrincipalPolicy,
            "TagInstanceProfile" => Iam::TagInstanceProfile,
            "TagMfaDevice" => Iam::TagMfaDevice,
            "TagOpenIdConnectProvider" => Iam::TagOpenIdConnectProvider,
            "TagPolicy" => Iam::TagPolicy,
            "TagRole" => Iam::TagRole,
            "TagSamlProvider" => Iam::TagSamlProvider,
            "TagServerCertificate" => Iam::TagServerCertificate,
            "TagUser" => Iam::TagUser,
            "UntagInstanceProfile" => Iam::UntagInstanceProfile,
            "UntagMfaDevice" => Iam::UntagMfaDevice,
            "UntagOpenIdConnectProvider" => Iam::UntagOpenIdConnectProvider,
            "UntagPolicy" => Iam::UntagPolicy,
            "UntagRole" => Iam::UntagRole,
            "UntagSamlProvider" => Iam::UntagSamlProvider,
            "UntagServerCertificate" => Iam::UntagServerCertificate,
            "UntagUser" => Iam::UntagUser,
            "UpdateAccessKey" => Iam::UpdateAccessKey,
            "UpdateAccountPasswordPolicy" => Iam::UpdateAccountPasswordPolicy,
            "UpdateAssumeRolePolicy" => Iam::UpdateAssumeRolePolicy,
            "UpdateGroup" => Iam::UpdateGroup,
            "UpdateLoginProfile" => Iam::UpdateLoginProfile,
            "UpdateOpenIdConnectProviderThumbprint" => Iam::UpdateOpenIdConnectProviderThumbprint,
            "UpdateRole" => Iam::UpdateRole,
            "UpdateRoleDescription" => Iam::UpdateRoleDescription,
            "UpdateSamlProvider" => Iam::UpdateSamlProvider,
            "UpdateServerCertificate" => Iam::UpdateServerCertificate,
            "UpdateServiceSpecificCredential" => Iam::UpdateServiceSpecificCredential,
            "UpdateSigningCertificate" => Iam::UpdateSigningCertificate,
            "UpdateSshPublicKey" => Iam::UpdateSshPublicKey,
            "UpdateUser" => Iam::UpdateUser,
            "UploadServerCertificate" => Iam::UploadServerCertificate,
            "UploadSigningCertificate" => Iam::UploadSigningCertificate,
            "UploadSshPublicKey" => Iam::UploadSshPublicKey,
            _ => Iam::Unknown,
        }
    }
}

fn unsupported(request_id: &str) -> HttpResponse {
    let out: IamResponse = IamApiError::internal_server_error(request_id, "The operation is unsupported at the moment.").into();
    HttpResponse::with_body(StatusCode::INTERNAL_SERVER_ERROR, BoxBody::new(out))
}

impl ServiceHandler for Iam {
    fn handle(self, req: &HttpRequest, params: HashMap<String, String>) -> HttpResponse {
        let request_id = Uuid::new_v4().to_string();
        // TODO: populate account ID from token
        let account_id = 1;

        let query_reader = QueryReader::new(params);
        let db = req.app_data::<Data<Database>>().expect("failed to get access to DB").as_ref();
        let mut response = match self {
            Iam::AddRoleToInstanceProfile => unsupported(&request_id),
            Iam::AddUserToGroup => unsupported(&request_id),
            Iam::AttachGroupPolicy => unsupported(&request_id),
            Iam::AttachRolePolicy => unsupported(&request_id),
            Iam::AttachUserPolicy => unsupported(&request_id),
            Iam::ChangePassword => unsupported(&request_id),
            Iam::CreateAccessKey => unsupported(&request_id),
            Iam::CreateAccountAlias => unsupported(&request_id),
            Iam::CreateGroup => unsupported(&request_id),
            Iam::CreateInstanceProfile => unsupported(&request_id),
            Iam::CreateLoginProfile => unsupported(&request_id),
            Iam::CreateOpenIdConnectProvider => unsupported(&request_id),
            Iam::CreatePolicy => {
                let output = block_on(Iam::create_policy(db, account_id, &request_id, query_reader));
                match output {
                    Ok(output) => {
                        let body: IamResponse = output.into();
                        HttpResponse::with_body(StatusCode::OK, BoxBody::new(body))
                    }
                    Err(err) => {
                        let error_code = err.error_code;
                        let body: IamResponse = err.into();
                        HttpResponse::with_body(error_code, BoxBody::new(body))
                    }
                }
            }
            Iam::CreatePolicyVersion => unsupported(&request_id),
            Iam::CreateRole => unsupported(&request_id),
            Iam::CreateSamlProvider => unsupported(&request_id),
            Iam::CreateServiceLinkedRole => unsupported(&request_id),
            Iam::CreateServiceSpecificCredential => unsupported(&request_id),
            Iam::CreateUser => {
                let output = block_on(Iam::create_user(db, account_id, request_id, query_reader)).unwrap();
                let body: String = output.into();
                HttpResponse::with_body(StatusCode::OK, BoxBody::new(body))
            }
            Iam::CreateVirtualMfaDevice => unsupported(&request_id),
            Iam::DeactivateMfaDevice => unsupported(&request_id),
            Iam::DeleteAccessKey => unsupported(&request_id),
            Iam::DeleteAccountAlias => unsupported(&request_id),
            Iam::DeleteAccountPasswordPolicy => unsupported(&request_id),
            Iam::DeleteGroup => unsupported(&request_id),
            Iam::DeleteGroupPolicy => unsupported(&request_id),
            Iam::DeleteInstanceProfile => unsupported(&request_id),
            Iam::DeleteLoginProfile => unsupported(&request_id),
            Iam::DeleteOpenIdConnectProvider => unsupported(&request_id),
            Iam::DeletePolicy => unsupported(&request_id),
            Iam::DeletePolicyVersion => unsupported(&request_id),
            Iam::DeleteRole => unsupported(&request_id),
            Iam::DeleteRolePermissionsBoundary => unsupported(&request_id),
            Iam::DeleteRolePolicy => unsupported(&request_id),
            Iam::DeleteSamlProvider => unsupported(&request_id),
            Iam::DeleteServerCertificate => unsupported(&request_id),
            Iam::DeleteServiceLinkedRole => unsupported(&request_id),
            Iam::DeleteServiceSpecificCredential => unsupported(&request_id),
            Iam::DeleteSigningCertificate => unsupported(&request_id),
            Iam::DeleteSshPublicKey => unsupported(&request_id),
            Iam::DeleteUser => unsupported(&request_id),
            Iam::DeleteUserPermissionsBoundary => unsupported(&request_id),
            Iam::DeleteUserPolicy => unsupported(&request_id),
            Iam::DeleteVirtualMfaDevice => unsupported(&request_id),
            Iam::DetachGroupPolicy => unsupported(&request_id),
            Iam::DetachRolePolicy => unsupported(&request_id),
            Iam::DetachUserPolicy => unsupported(&request_id),
            Iam::EnableMfaDevice => unsupported(&request_id),
            Iam::GenerateCredentialReport => unsupported(&request_id),
            Iam::GenerateOrganizationsAccessReport => unsupported(&request_id),
            Iam::GenerateServiceLastAccessedDetails => unsupported(&request_id),
            Iam::GetAccessKeyLastUsed => unsupported(&request_id),
            Iam::GetAccountAuthorizationDetails => unsupported(&request_id),
            Iam::GetAccountPasswordPolicy => unsupported(&request_id),
            Iam::GetAccountSummary => unsupported(&request_id),
            Iam::GetContextKeysForCustomPolicy => unsupported(&request_id),
            Iam::GetContextKeysForPrincipalPolicy => unsupported(&request_id),
            Iam::GetCredentialReport => unsupported(&request_id),
            Iam::GetGroup => unsupported(&request_id),
            Iam::GetGroupPolicy => unsupported(&request_id),
            Iam::GetInstanceProfile => unsupported(&request_id),
            Iam::GetLoginProfile => unsupported(&request_id),
            Iam::GetMfaDevice => unsupported(&request_id),
            Iam::GetOpenIdConnectProvider => unsupported(&request_id),
            Iam::GetOrganizationsAccessReport => unsupported(&request_id),
            Iam::GetPaginator => unsupported(&request_id),
            Iam::GetPolicy => unsupported(&request_id),
            Iam::GetPolicyVersion => unsupported(&request_id),
            Iam::GetRole => unsupported(&request_id),
            Iam::GetRolePolicy => unsupported(&request_id),
            Iam::GetSamlProvider => unsupported(&request_id),
            Iam::GetServerCertificate => unsupported(&request_id),
            Iam::GetServiceLastAccessedDetails => unsupported(&request_id),
            Iam::GetServiceLastAccessedDetailsWithEntities => unsupported(&request_id),
            Iam::GetServiceLinkedRoleDeletionStatus => unsupported(&request_id),
            Iam::GetSshPublicKey => unsupported(&request_id),
            Iam::GetUser => unsupported(&request_id),
            Iam::GetUserPolicy => unsupported(&request_id),
            Iam::GetWaiter => unsupported(&request_id),
            Iam::ListAccessKeys => unsupported(&request_id),
            Iam::ListAccountAliases => unsupported(&request_id),
            Iam::ListAttachedGroupPolicies => unsupported(&request_id),
            Iam::ListAttachedRolePolicies => unsupported(&request_id),
            Iam::ListAttachedUserPolicies => unsupported(&request_id),
            Iam::ListEntitiesForPolicy => unsupported(&request_id),
            Iam::ListGroupPolicies => unsupported(&request_id),
            Iam::ListGroups => unsupported(&request_id),
            Iam::ListGroupsForUser => unsupported(&request_id),
            Iam::ListInstanceProfileTags => unsupported(&request_id),
            Iam::ListInstanceProfiles => unsupported(&request_id),
            Iam::ListInstanceProfilesForRole => unsupported(&request_id),
            Iam::ListMfaDeviceTags => unsupported(&request_id),
            Iam::ListMfaDevices => unsupported(&request_id),
            Iam::ListOpenIdConnectProviderTags => unsupported(&request_id),
            Iam::ListOpenIdConnectProviders => unsupported(&request_id),
            Iam::ListPolicies => unsupported(&request_id),
            Iam::ListPoliciesGrantingServiceAccess => unsupported(&request_id),
            Iam::ListPolicyTags => unsupported(&request_id),
            Iam::ListPolicyVersions => unsupported(&request_id),
            Iam::ListRolePolicies => unsupported(&request_id),
            Iam::ListRoleTags => unsupported(&request_id),
            Iam::ListRoles => unsupported(&request_id),
            Iam::ListSamlProviderTags => unsupported(&request_id),
            Iam::ListSamlProviders => unsupported(&request_id),
            Iam::ListServerCertificateTags => unsupported(&request_id),
            Iam::ListServerCertificates => unsupported(&request_id),
            Iam::ListServiceSpecificCredentials => unsupported(&request_id),
            Iam::ListSigningCertificates => unsupported(&request_id),
            Iam::ListSshPublicKeys => unsupported(&request_id),
            Iam::ListUserPolicies => unsupported(&request_id),
            Iam::ListUserTags => unsupported(&request_id),
            Iam::ListUsers => unsupported(&request_id),
            Iam::ListVirtualMfaDevices => unsupported(&request_id),
            Iam::PutGroupPolicy => unsupported(&request_id),
            Iam::PutRolePermissionsBoundary => unsupported(&request_id),
            Iam::PutRolePolicy => unsupported(&request_id),
            Iam::PutUserPermissionsBoundary => unsupported(&request_id),
            Iam::PutUserPolicy => unsupported(&request_id),
            Iam::RemoveClientIdFromOpenIdConnectProvider => unsupported(&request_id),
            Iam::RemoveRoleFromInstanceProfile => unsupported(&request_id),
            Iam::RemoveUserFromGroup => unsupported(&request_id),
            Iam::ResetServiceSpecificCredential => unsupported(&request_id),
            Iam::ResyncMfaDevice => unsupported(&request_id),
            Iam::SetDefaultPolicyVersion => unsupported(&request_id),
            Iam::SetSecurityTokenServicePreferences => unsupported(&request_id),
            Iam::SimulateCustomPolicy => unsupported(&request_id),
            Iam::SimulatePrincipalPolicy => unsupported(&request_id),
            Iam::TagInstanceProfile => unsupported(&request_id),
            Iam::TagMfaDevice => unsupported(&request_id),
            Iam::TagOpenIdConnectProvider => unsupported(&request_id),
            Iam::TagPolicy => unsupported(&request_id),
            Iam::TagRole => unsupported(&request_id),
            Iam::TagSamlProvider => unsupported(&request_id),
            Iam::TagServerCertificate => unsupported(&request_id),
            Iam::TagUser => unsupported(&request_id),
            Iam::UntagInstanceProfile => unsupported(&request_id),
            Iam::UntagMfaDevice => unsupported(&request_id),
            Iam::UntagOpenIdConnectProvider => unsupported(&request_id),
            Iam::UntagPolicy => unsupported(&request_id),
            Iam::UntagRole => unsupported(&request_id),
            Iam::UntagSamlProvider => unsupported(&request_id),
            Iam::UntagServerCertificate => unsupported(&request_id),
            Iam::UntagUser => unsupported(&request_id),
            Iam::UpdateAccessKey => unsupported(&request_id),
            Iam::UpdateAccountPasswordPolicy => unsupported(&request_id),
            Iam::UpdateAssumeRolePolicy => unsupported(&request_id),
            Iam::UpdateGroup => unsupported(&request_id),
            Iam::UpdateLoginProfile => unsupported(&request_id),
            Iam::UpdateOpenIdConnectProviderThumbprint => unsupported(&request_id),
            Iam::UpdateRole => unsupported(&request_id),
            Iam::UpdateRoleDescription => unsupported(&request_id),
            Iam::UpdateSamlProvider => unsupported(&request_id),
            Iam::UpdateServerCertificate => unsupported(&request_id),
            Iam::UpdateServiceSpecificCredential => unsupported(&request_id),
            Iam::UpdateSigningCertificate => unsupported(&request_id),
            Iam::UpdateSshPublicKey => unsupported(&request_id),
            Iam::UpdateUser => unsupported(&request_id),
            Iam::UploadServerCertificate => unsupported(&request_id),
            Iam::UploadSigningCertificate => unsupported(&request_id),
            Iam::UploadSshPublicKey => unsupported(&request_id),
            _ => unsupported(&request_id),
        };
        response
            .headers_mut()
            .append(HeaderName::from_static("content-type"), HeaderValue::from_static("application/xml"));
        return response;
    }
}
