[workspace]
members = [
    "local_cloud_smithy_gen",
    "local_cloud_common",
    "local_cloud_xml",
    "local_cloud_db",
    "local_cloud_iam_policy_document",
    "local_cloud_iam_rs",
    "local_cloud_sts_rs",
]
resolver = "2"

[workspace.dependencies]
actix = "0.13"
actix-broker = "0.4"
actix-codec = "0.5"
actix-http = "3"
actix-server = "2.3"
actix-service = "2"
actix-multipart = "0.6"
actix-multipart-derive = "0.6"
actix-test = "0.1"
actix-tls = "3"
actix-utils = "3"
actix-web = "4.3"
actix-web-actors = "4.1"
actix-ws = "0.2.5"
awc = "3"

derive_more = "0.99.7"
derive_builder = "0.12.0"
dotenv = "0.15"
env_logger = "0.10"
futures = "*"
futures-util = { version = "0.3.17", default-features = false, features = [
    "std",
] }
log = "0.4"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
validator = { version = "0.16.1", features = ["derive"] }

sqlx = { version = "0.7.3", features = [
    "runtime-async-std-native-tls",
    "sqlite",
    "chrono",
    "uuid",
] }
tokio = { version = "1.24.2", features = ["sync", "full"] }
url = "2.3.1"

chrono = { version = "0.4.24", features = ["serde"] }

aws-config = "1.1.1"
aws-smithy-xml = "0.60.1"
aws-smithy-types = "1.1.1"
aws-sdk-iam = "1.9.0"
aws-sdk-sts = "1.9.0"
aws-credential-types = "1.1.1"

uuid = { version = "1", features = ["v4", "serde"] }
rand = "0.8.5"
parking_lot = "0.12.1"

etcd-client = "0.12.1"
