indent_style = "Block"
reorder_imports = true
newline_style = "Unix"
fn_call_width = 120
max_width = 120
# fn_call_style = "Compressed"
fn_params_layout = "Compressed"
error_on_line_overflow = true
error_on_unformatted = true
